eureka:
  client:
    service-url:
      default-zone: http://localhost:8761


spring:
  cloud:
    gateway:
      routes:
        - id: courseServiceCrud
          uri: lb://COURSE-CRUD-SERVICE
          predicates:
            - Path=/course-service/**
        - id: courseServiceGet
          uri: lb://COURSE-GET-SERVICE
          predicates:
            - Path=/course-api-all/**
    

      
server:
  port: 9000